version: "3" 
services:
  pls-mycat:
    image: pls/pls-mycat:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      swarm-overlay:
        aliases:
          - pls-mycat
    ports:
     - 18066:8066
     - 19066:9066
networks:
  swarm-overlay:
    external:
      name: swarm-overlay
  
