version: "3"
services:
  pls:
    image: pls:1.0
    # 去阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-admin-system-0.0.1
    #container_name: micro-cloud-admin-system
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      pls-overlay:
        aliases:
          - pls-service
    ports:
      - 8888:8888
      # 有值的时候，才能够放开
      # environment:
      # 在Dockerfile文件里面定义的参数可以在这里输入
      #- PROFILE=dev
networks:
  pls-overlay:
    external:
      name: pls-overlay