server:
  port: 10002
#jasypt:
#  encryptor:
#    password: EWRREWRERWECCCXC
#    algorithm: PBEWithMD5AndDES
spring:
  datasource:
    druid:
      url: jdbc:mysql://172.16.106.9:30060/pls_dev?characterEncoding=utf-8
      username: root #ENC(2k8q52zaqcBOkSyj1NVOvg==) #root
      password: abc123 #ENC(BqHQrbzTYCTaQRzonzHpYA==) #abc123
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      driver-class-name: com.mysql.jdbc.Driver
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          config:
            delete-allow: false
            drop-table-allow: false
          db-type: mysql
          enabled: true
      initial-size: 5
      max-active: 100
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 100000
      min-idle: 5
      pool-prepared-statements: true
      stat-view-servlet:
        allow: 172.30.20.106
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
