package com.jiashi.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QcInspectionHeaderCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public QcInspectionHeaderCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShipBatchIsNull() {
            addCriterion("SHIP_BATCH is null");
            return (Criteria) this;
        }

        public Criteria andShipBatchIsNotNull() {
            addCriterion("SHIP_BATCH is not null");
            return (Criteria) this;
        }

        public Criteria andShipBatchEqualTo(String value) {
            addCriterion("SHIP_BATCH =", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchNotEqualTo(String value) {
            addCriterion("SHIP_BATCH <>", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchGreaterThan(String value) {
            addCriterion("SHIP_BATCH >", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchGreaterThanOrEqualTo(String value) {
            addCriterion("SHIP_BATCH >=", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchLessThan(String value) {
            addCriterion("SHIP_BATCH <", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchLessThanOrEqualTo(String value) {
            addCriterion("SHIP_BATCH <=", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchLike(String value) {
            addCriterion("SHIP_BATCH like", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchNotLike(String value) {
            addCriterion("SHIP_BATCH not like", value, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchIn(List<String> values) {
            addCriterion("SHIP_BATCH in", values, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchNotIn(List<String> values) {
            addCriterion("SHIP_BATCH not in", values, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchBetween(String value1, String value2) {
            addCriterion("SHIP_BATCH between", value1, value2, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andShipBatchNotBetween(String value1, String value2) {
            addCriterion("SHIP_BATCH not between", value1, value2, "shipBatch");
            return (Criteria) this;
        }

        public Criteria andFabricTypeIsNull() {
            addCriterion("FABRIC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFabricTypeIsNotNull() {
            addCriterion("FABRIC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFabricTypeEqualTo(String value) {
            addCriterion("FABRIC_TYPE =", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeNotEqualTo(String value) {
            addCriterion("FABRIC_TYPE <>", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeGreaterThan(String value) {
            addCriterion("FABRIC_TYPE >", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FABRIC_TYPE >=", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeLessThan(String value) {
            addCriterion("FABRIC_TYPE <", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeLessThanOrEqualTo(String value) {
            addCriterion("FABRIC_TYPE <=", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeLike(String value) {
            addCriterion("FABRIC_TYPE like", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeNotLike(String value) {
            addCriterion("FABRIC_TYPE not like", value, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeIn(List<String> values) {
            addCriterion("FABRIC_TYPE in", values, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeNotIn(List<String> values) {
            addCriterion("FABRIC_TYPE not in", values, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeBetween(String value1, String value2) {
            addCriterion("FABRIC_TYPE between", value1, value2, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricTypeNotBetween(String value1, String value2) {
            addCriterion("FABRIC_TYPE not between", value1, value2, "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricNoIsNull() {
            addCriterion("FABRIC_NO is null");
            return (Criteria) this;
        }

        public Criteria andFabricNoIsNotNull() {
            addCriterion("FABRIC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFabricNoEqualTo(String value) {
            addCriterion("FABRIC_NO =", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoNotEqualTo(String value) {
            addCriterion("FABRIC_NO <>", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoGreaterThan(String value) {
            addCriterion("FABRIC_NO >", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoGreaterThanOrEqualTo(String value) {
            addCriterion("FABRIC_NO >=", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoLessThan(String value) {
            addCriterion("FABRIC_NO <", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoLessThanOrEqualTo(String value) {
            addCriterion("FABRIC_NO <=", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoLike(String value) {
            addCriterion("FABRIC_NO like", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoNotLike(String value) {
            addCriterion("FABRIC_NO not like", value, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoIn(List<String> values) {
            addCriterion("FABRIC_NO in", values, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoNotIn(List<String> values) {
            addCriterion("FABRIC_NO not in", values, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoBetween(String value1, String value2) {
            addCriterion("FABRIC_NO between", value1, value2, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andFabricNoNotBetween(String value1, String value2) {
            addCriterion("FABRIC_NO not between", value1, value2, "fabricNo");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("COLOR is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("COLOR is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("COLOR =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("COLOR <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("COLOR >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("COLOR >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("COLOR <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("COLOR <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("COLOR like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("COLOR not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("COLOR in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("COLOR not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("COLOR between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("COLOR not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andMatGrpIsNull() {
            addCriterion("MAT_GRP is null");
            return (Criteria) this;
        }

        public Criteria andMatGrpIsNotNull() {
            addCriterion("MAT_GRP is not null");
            return (Criteria) this;
        }

        public Criteria andMatGrpEqualTo(String value) {
            addCriterion("MAT_GRP =", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpNotEqualTo(String value) {
            addCriterion("MAT_GRP <>", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpGreaterThan(String value) {
            addCriterion("MAT_GRP >", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpGreaterThanOrEqualTo(String value) {
            addCriterion("MAT_GRP >=", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpLessThan(String value) {
            addCriterion("MAT_GRP <", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpLessThanOrEqualTo(String value) {
            addCriterion("MAT_GRP <=", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpLike(String value) {
            addCriterion("MAT_GRP like", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpNotLike(String value) {
            addCriterion("MAT_GRP not like", value, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpIn(List<String> values) {
            addCriterion("MAT_GRP in", values, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpNotIn(List<String> values) {
            addCriterion("MAT_GRP not in", values, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpBetween(String value1, String value2) {
            addCriterion("MAT_GRP between", value1, value2, "matGrp");
            return (Criteria) this;
        }

        public Criteria andMatGrpNotBetween(String value1, String value2) {
            addCriterion("MAT_GRP not between", value1, value2, "matGrp");
            return (Criteria) this;
        }

        public Criteria andCustomerIsNull() {
            addCriterion("CUSTOMER is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIsNotNull() {
            addCriterion("CUSTOMER is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerEqualTo(String value) {
            addCriterion("CUSTOMER =", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerNotEqualTo(String value) {
            addCriterion("CUSTOMER <>", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerGreaterThan(String value) {
            addCriterion("CUSTOMER >", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER >=", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerLessThan(String value) {
            addCriterion("CUSTOMER <", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER <=", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerLike(String value) {
            addCriterion("CUSTOMER like", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerNotLike(String value) {
            addCriterion("CUSTOMER not like", value, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerIn(List<String> values) {
            addCriterion("CUSTOMER in", values, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerNotIn(List<String> values) {
            addCriterion("CUSTOMER not in", values, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerBetween(String value1, String value2) {
            addCriterion("CUSTOMER between", value1, value2, "customer");
            return (Criteria) this;
        }

        public Criteria andCustomerNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER not between", value1, value2, "customer");
            return (Criteria) this;
        }

        public Criteria andRollModeIsNull() {
            addCriterion("ROLL_MODE is null");
            return (Criteria) this;
        }

        public Criteria andRollModeIsNotNull() {
            addCriterion("ROLL_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andRollModeEqualTo(String value) {
            addCriterion("ROLL_MODE =", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeNotEqualTo(String value) {
            addCriterion("ROLL_MODE <>", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeGreaterThan(String value) {
            addCriterion("ROLL_MODE >", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeGreaterThanOrEqualTo(String value) {
            addCriterion("ROLL_MODE >=", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeLessThan(String value) {
            addCriterion("ROLL_MODE <", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeLessThanOrEqualTo(String value) {
            addCriterion("ROLL_MODE <=", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeLike(String value) {
            addCriterion("ROLL_MODE like", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeNotLike(String value) {
            addCriterion("ROLL_MODE not like", value, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeIn(List<String> values) {
            addCriterion("ROLL_MODE in", values, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeNotIn(List<String> values) {
            addCriterion("ROLL_MODE not in", values, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeBetween(String value1, String value2) {
            addCriterion("ROLL_MODE between", value1, value2, "rollMode");
            return (Criteria) this;
        }

        public Criteria andRollModeNotBetween(String value1, String value2) {
            addCriterion("ROLL_MODE not between", value1, value2, "rollMode");
            return (Criteria) this;
        }

        public Criteria andConditionIsNull() {
            addCriterion("CONDITION is null");
            return (Criteria) this;
        }

        public Criteria andConditionIsNotNull() {
            addCriterion("CONDITION is not null");
            return (Criteria) this;
        }

        public Criteria andConditionEqualTo(String value) {
            addCriterion("CONDITION =", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotEqualTo(String value) {
            addCriterion("CONDITION <>", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionGreaterThan(String value) {
            addCriterion("CONDITION >", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionGreaterThanOrEqualTo(String value) {
            addCriterion("CONDITION >=", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLessThan(String value) {
            addCriterion("CONDITION <", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLessThanOrEqualTo(String value) {
            addCriterion("CONDITION <=", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLike(String value) {
            addCriterion("CONDITION like", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotLike(String value) {
            addCriterion("CONDITION not like", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionIn(List<String> values) {
            addCriterion("CONDITION in", values, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotIn(List<String> values) {
            addCriterion("CONDITION not in", values, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionBetween(String value1, String value2) {
            addCriterion("CONDITION between", value1, value2, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotBetween(String value1, String value2) {
            addCriterion("CONDITION not between", value1, value2, "condition");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorIsNull() {
            addCriterion("CORRECTION_FACTOR is null");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorIsNotNull() {
            addCriterion("CORRECTION_FACTOR is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorEqualTo(BigDecimal value) {
            addCriterion("CORRECTION_FACTOR =", value, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorNotEqualTo(BigDecimal value) {
            addCriterion("CORRECTION_FACTOR <>", value, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorGreaterThan(BigDecimal value) {
            addCriterion("CORRECTION_FACTOR >", value, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CORRECTION_FACTOR >=", value, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorLessThan(BigDecimal value) {
            addCriterion("CORRECTION_FACTOR <", value, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CORRECTION_FACTOR <=", value, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorIn(List<BigDecimal> values) {
            addCriterion("CORRECTION_FACTOR in", values, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorNotIn(List<BigDecimal> values) {
            addCriterion("CORRECTION_FACTOR not in", values, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CORRECTION_FACTOR between", value1, value2, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andCorrectionFactorNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CORRECTION_FACTOR not between", value1, value2, "correctionFactor");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfIsNull() {
            addCriterion("WEIGHT_LEN_CF is null");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfIsNotNull() {
            addCriterion("WEIGHT_LEN_CF is not null");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfEqualTo(BigDecimal value) {
            addCriterion("WEIGHT_LEN_CF =", value, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfNotEqualTo(BigDecimal value) {
            addCriterion("WEIGHT_LEN_CF <>", value, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfGreaterThan(BigDecimal value) {
            addCriterion("WEIGHT_LEN_CF >", value, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("WEIGHT_LEN_CF >=", value, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfLessThan(BigDecimal value) {
            addCriterion("WEIGHT_LEN_CF <", value, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfLessThanOrEqualTo(BigDecimal value) {
            addCriterion("WEIGHT_LEN_CF <=", value, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfIn(List<BigDecimal> values) {
            addCriterion("WEIGHT_LEN_CF in", values, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfNotIn(List<BigDecimal> values) {
            addCriterion("WEIGHT_LEN_CF not in", values, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WEIGHT_LEN_CF between", value1, value2, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andWeightLenCfNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WEIGHT_LEN_CF not between", value1, value2, "weightLenCf");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightIsNull() {
            addCriterion("REQUIRED_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightIsNotNull() {
            addCriterion("REQUIRED_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightEqualTo(BigDecimal value) {
            addCriterion("REQUIRED_WEIGHT =", value, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightNotEqualTo(BigDecimal value) {
            addCriterion("REQUIRED_WEIGHT <>", value, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightGreaterThan(BigDecimal value) {
            addCriterion("REQUIRED_WEIGHT >", value, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REQUIRED_WEIGHT >=", value, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightLessThan(BigDecimal value) {
            addCriterion("REQUIRED_WEIGHT <", value, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REQUIRED_WEIGHT <=", value, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightIn(List<BigDecimal> values) {
            addCriterion("REQUIRED_WEIGHT in", values, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightNotIn(List<BigDecimal> values) {
            addCriterion("REQUIRED_WEIGHT not in", values, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REQUIRED_WEIGHT between", value1, value2, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andRequiredWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REQUIRED_WEIGHT not between", value1, value2, "requiredWeight");
            return (Criteria) this;
        }

        public Criteria andCreateduserIsNull() {
            addCriterion("CREATEDUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateduserIsNotNull() {
            addCriterion("CREATEDUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateduserEqualTo(String value) {
            addCriterion("CREATEDUSER =", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotEqualTo(String value) {
            addCriterion("CREATEDUSER <>", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserGreaterThan(String value) {
            addCriterion("CREATEDUSER >", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDUSER >=", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserLessThan(String value) {
            addCriterion("CREATEDUSER <", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserLessThanOrEqualTo(String value) {
            addCriterion("CREATEDUSER <=", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserLike(String value) {
            addCriterion("CREATEDUSER like", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotLike(String value) {
            addCriterion("CREATEDUSER not like", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserIn(List<String> values) {
            addCriterion("CREATEDUSER in", values, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotIn(List<String> values) {
            addCriterion("CREATEDUSER not in", values, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserBetween(String value1, String value2) {
            addCriterion("CREATEDUSER between", value1, value2, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotBetween(String value1, String value2) {
            addCriterion("CREATEDUSER not between", value1, value2, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNull() {
            addCriterion("CREATEDDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNotNull() {
            addCriterion("CREATEDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateddateEqualTo(Date value) {
            addCriterion("CREATEDDATE =", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotEqualTo(Date value) {
            addCriterion("CREATEDDATE <>", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThan(Date value) {
            addCriterion("CREATEDDATE >", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDDATE >=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThan(Date value) {
            addCriterion("CREATEDDATE <", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDDATE <=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateIn(List<Date> values) {
            addCriterion("CREATEDDATE in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotIn(List<Date> values) {
            addCriterion("CREATEDDATE not in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateBetween(Date value1, Date value2) {
            addCriterion("CREATEDDATE between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDDATE not between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserIsNull() {
            addCriterion("LSTUPDATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserIsNotNull() {
            addCriterion("LSTUPDATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserEqualTo(String value) {
            addCriterion("LSTUPDATEUSER =", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserNotEqualTo(String value) {
            addCriterion("LSTUPDATEUSER <>", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserGreaterThan(String value) {
            addCriterion("LSTUPDATEUSER >", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("LSTUPDATEUSER >=", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserLessThan(String value) {
            addCriterion("LSTUPDATEUSER <", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserLessThanOrEqualTo(String value) {
            addCriterion("LSTUPDATEUSER <=", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserLike(String value) {
            addCriterion("LSTUPDATEUSER like", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserNotLike(String value) {
            addCriterion("LSTUPDATEUSER not like", value, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserIn(List<String> values) {
            addCriterion("LSTUPDATEUSER in", values, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserNotIn(List<String> values) {
            addCriterion("LSTUPDATEUSER not in", values, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserBetween(String value1, String value2) {
            addCriterion("LSTUPDATEUSER between", value1, value2, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserNotBetween(String value1, String value2) {
            addCriterion("LSTUPDATEUSER not between", value1, value2, "lstupdateuser");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateIsNull() {
            addCriterion("LSTUPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateIsNotNull() {
            addCriterion("LSTUPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateEqualTo(Date value) {
            addCriterion("LSTUPDATEDATE =", value, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateNotEqualTo(Date value) {
            addCriterion("LSTUPDATEDATE <>", value, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateGreaterThan(Date value) {
            addCriterion("LSTUPDATEDATE >", value, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("LSTUPDATEDATE >=", value, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateLessThan(Date value) {
            addCriterion("LSTUPDATEDATE <", value, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateLessThanOrEqualTo(Date value) {
            addCriterion("LSTUPDATEDATE <=", value, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateIn(List<Date> values) {
            addCriterion("LSTUPDATEDATE in", values, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateNotIn(List<Date> values) {
            addCriterion("LSTUPDATEDATE not in", values, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateBetween(Date value1, Date value2) {
            addCriterion("LSTUPDATEDATE between", value1, value2, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andLstupdatedateNotBetween(Date value1, Date value2) {
            addCriterion("LSTUPDATEDATE not between", value1, value2, "lstupdatedate");
            return (Criteria) this;
        }

        public Criteria andShipBatchLikeInsensitive(String value) {
            addCriterion("upper(SHIP_BATCH) like", value.toUpperCase(), "shipBatch");
            return (Criteria) this;
        }

        public Criteria andFabricTypeLikeInsensitive(String value) {
            addCriterion("upper(FABRIC_TYPE) like", value.toUpperCase(), "fabricType");
            return (Criteria) this;
        }

        public Criteria andFabricNoLikeInsensitive(String value) {
            addCriterion("upper(FABRIC_NO) like", value.toUpperCase(), "fabricNo");
            return (Criteria) this;
        }

        public Criteria andColorLikeInsensitive(String value) {
            addCriterion("upper(COLOR) like", value.toUpperCase(), "color");
            return (Criteria) this;
        }

        public Criteria andMatGrpLikeInsensitive(String value) {
            addCriterion("upper(MAT_GRP) like", value.toUpperCase(), "matGrp");
            return (Criteria) this;
        }

        public Criteria andCustomerLikeInsensitive(String value) {
            addCriterion("upper(CUSTOMER) like", value.toUpperCase(), "customer");
            return (Criteria) this;
        }

        public Criteria andRollModeLikeInsensitive(String value) {
            addCriterion("upper(ROLL_MODE) like", value.toUpperCase(), "rollMode");
            return (Criteria) this;
        }

        public Criteria andConditionLikeInsensitive(String value) {
            addCriterion("upper(CONDITION) like", value.toUpperCase(), "condition");
            return (Criteria) this;
        }

        public Criteria andCreateduserLikeInsensitive(String value) {
            addCriterion("upper(CREATEDUSER) like", value.toUpperCase(), "createduser");
            return (Criteria) this;
        }

        public Criteria andLstupdateuserLikeInsensitive(String value) {
            addCriterion("upper(LSTUPDATEUSER) like", value.toUpperCase(), "lstupdateuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}