package com.jiashi.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class QcInspectionHeader implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.SHIP_BATCH
     *
     * @mbg.generated
     */
    private String shipBatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.FABRIC_TYPE
     *
     * @mbg.generated
     */
    private String fabricType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.FABRIC_NO
     *
     * @mbg.generated
     */
    private String fabricNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.COLOR
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.MAT_GRP
     *
     * @mbg.generated
     */
    private String matGrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.CUSTOMER
     *
     * @mbg.generated
     */
    private String customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.ROLL_MODE
     *
     * @mbg.generated
     */
    private String rollMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.CONDITION
     *
     * @mbg.generated
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.CORRECTION_FACTOR
     *
     * @mbg.generated
     */
    private BigDecimal correctionFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.WEIGHT_LEN_CF
     *
     * @mbg.generated
     */
    private BigDecimal weightLenCf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.REQUIRED_WEIGHT
     *
     * @mbg.generated
     */
    private BigDecimal requiredWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.CREATEDUSER
     *
     * @mbg.generated
     */
    private String createduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.CREATEDDATE
     *
     * @mbg.generated
     */
    private Date createddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.LSTUPDATEUSER
     *
     * @mbg.generated
     */
    private String lstupdateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QC_INSPECTION_HEADER.LSTUPDATEDATE
     *
     * @mbg.generated
     */
    private Date lstupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.SHIP_BATCH
     *
     * @return the value of QC_INSPECTION_HEADER.SHIP_BATCH
     *
     * @mbg.generated
     */
    public String getShipBatch() {
        return shipBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.SHIP_BATCH
     *
     * @param shipBatch the value for QC_INSPECTION_HEADER.SHIP_BATCH
     *
     * @mbg.generated
     */
    public void setShipBatch(String shipBatch) {
        this.shipBatch = shipBatch == null ? null : shipBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.FABRIC_TYPE
     *
     * @return the value of QC_INSPECTION_HEADER.FABRIC_TYPE
     *
     * @mbg.generated
     */
    public String getFabricType() {
        return fabricType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.FABRIC_TYPE
     *
     * @param fabricType the value for QC_INSPECTION_HEADER.FABRIC_TYPE
     *
     * @mbg.generated
     */
    public void setFabricType(String fabricType) {
        this.fabricType = fabricType == null ? null : fabricType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.FABRIC_NO
     *
     * @return the value of QC_INSPECTION_HEADER.FABRIC_NO
     *
     * @mbg.generated
     */
    public String getFabricNo() {
        return fabricNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.FABRIC_NO
     *
     * @param fabricNo the value for QC_INSPECTION_HEADER.FABRIC_NO
     *
     * @mbg.generated
     */
    public void setFabricNo(String fabricNo) {
        this.fabricNo = fabricNo == null ? null : fabricNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.COLOR
     *
     * @return the value of QC_INSPECTION_HEADER.COLOR
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.COLOR
     *
     * @param color the value for QC_INSPECTION_HEADER.COLOR
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.MAT_GRP
     *
     * @return the value of QC_INSPECTION_HEADER.MAT_GRP
     *
     * @mbg.generated
     */
    public String getMatGrp() {
        return matGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.MAT_GRP
     *
     * @param matGrp the value for QC_INSPECTION_HEADER.MAT_GRP
     *
     * @mbg.generated
     */
    public void setMatGrp(String matGrp) {
        this.matGrp = matGrp == null ? null : matGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.CUSTOMER
     *
     * @return the value of QC_INSPECTION_HEADER.CUSTOMER
     *
     * @mbg.generated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.CUSTOMER
     *
     * @param customer the value for QC_INSPECTION_HEADER.CUSTOMER
     *
     * @mbg.generated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.ROLL_MODE
     *
     * @return the value of QC_INSPECTION_HEADER.ROLL_MODE
     *
     * @mbg.generated
     */
    public String getRollMode() {
        return rollMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.ROLL_MODE
     *
     * @param rollMode the value for QC_INSPECTION_HEADER.ROLL_MODE
     *
     * @mbg.generated
     */
    public void setRollMode(String rollMode) {
        this.rollMode = rollMode == null ? null : rollMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.CONDITION
     *
     * @return the value of QC_INSPECTION_HEADER.CONDITION
     *
     * @mbg.generated
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.CONDITION
     *
     * @param condition the value for QC_INSPECTION_HEADER.CONDITION
     *
     * @mbg.generated
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.CORRECTION_FACTOR
     *
     * @return the value of QC_INSPECTION_HEADER.CORRECTION_FACTOR
     *
     * @mbg.generated
     */
    public BigDecimal getCorrectionFactor() {
        return correctionFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.CORRECTION_FACTOR
     *
     * @param correctionFactor the value for QC_INSPECTION_HEADER.CORRECTION_FACTOR
     *
     * @mbg.generated
     */
    public void setCorrectionFactor(BigDecimal correctionFactor) {
        this.correctionFactor = correctionFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.WEIGHT_LEN_CF
     *
     * @return the value of QC_INSPECTION_HEADER.WEIGHT_LEN_CF
     *
     * @mbg.generated
     */
    public BigDecimal getWeightLenCf() {
        return weightLenCf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.WEIGHT_LEN_CF
     *
     * @param weightLenCf the value for QC_INSPECTION_HEADER.WEIGHT_LEN_CF
     *
     * @mbg.generated
     */
    public void setWeightLenCf(BigDecimal weightLenCf) {
        this.weightLenCf = weightLenCf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.REQUIRED_WEIGHT
     *
     * @return the value of QC_INSPECTION_HEADER.REQUIRED_WEIGHT
     *
     * @mbg.generated
     */
    public BigDecimal getRequiredWeight() {
        return requiredWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.REQUIRED_WEIGHT
     *
     * @param requiredWeight the value for QC_INSPECTION_HEADER.REQUIRED_WEIGHT
     *
     * @mbg.generated
     */
    public void setRequiredWeight(BigDecimal requiredWeight) {
        this.requiredWeight = requiredWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.CREATEDUSER
     *
     * @return the value of QC_INSPECTION_HEADER.CREATEDUSER
     *
     * @mbg.generated
     */
    public String getCreateduser() {
        return createduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.CREATEDUSER
     *
     * @param createduser the value for QC_INSPECTION_HEADER.CREATEDUSER
     *
     * @mbg.generated
     */
    public void setCreateduser(String createduser) {
        this.createduser = createduser == null ? null : createduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.CREATEDDATE
     *
     * @return the value of QC_INSPECTION_HEADER.CREATEDDATE
     *
     * @mbg.generated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.CREATEDDATE
     *
     * @param createddate the value for QC_INSPECTION_HEADER.CREATEDDATE
     *
     * @mbg.generated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.LSTUPDATEUSER
     *
     * @return the value of QC_INSPECTION_HEADER.LSTUPDATEUSER
     *
     * @mbg.generated
     */
    public String getLstupdateuser() {
        return lstupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.LSTUPDATEUSER
     *
     * @param lstupdateuser the value for QC_INSPECTION_HEADER.LSTUPDATEUSER
     *
     * @mbg.generated
     */
    public void setLstupdateuser(String lstupdateuser) {
        this.lstupdateuser = lstupdateuser == null ? null : lstupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QC_INSPECTION_HEADER.LSTUPDATEDATE
     *
     * @return the value of QC_INSPECTION_HEADER.LSTUPDATEDATE
     *
     * @mbg.generated
     */
    public Date getLstupdatedate() {
        return lstupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QC_INSPECTION_HEADER.LSTUPDATEDATE
     *
     * @param lstupdatedate the value for QC_INSPECTION_HEADER.LSTUPDATEDATE
     *
     * @mbg.generated
     */
    public void setLstupdatedate(Date lstupdatedate) {
        this.lstupdatedate = lstupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QcInspectionHeader other = (QcInspectionHeader) that;
        return (this.getShipBatch() == null ? other.getShipBatch() == null : this.getShipBatch().equals(other.getShipBatch()))
            && (this.getFabricType() == null ? other.getFabricType() == null : this.getFabricType().equals(other.getFabricType()))
            && (this.getFabricNo() == null ? other.getFabricNo() == null : this.getFabricNo().equals(other.getFabricNo()))
            && (this.getColor() == null ? other.getColor() == null : this.getColor().equals(other.getColor()))
            && (this.getMatGrp() == null ? other.getMatGrp() == null : this.getMatGrp().equals(other.getMatGrp()))
            && (this.getCustomer() == null ? other.getCustomer() == null : this.getCustomer().equals(other.getCustomer()))
            && (this.getRollMode() == null ? other.getRollMode() == null : this.getRollMode().equals(other.getRollMode()))
            && (this.getCondition() == null ? other.getCondition() == null : this.getCondition().equals(other.getCondition()))
            && (this.getCorrectionFactor() == null ? other.getCorrectionFactor() == null : this.getCorrectionFactor().equals(other.getCorrectionFactor()))
            && (this.getWeightLenCf() == null ? other.getWeightLenCf() == null : this.getWeightLenCf().equals(other.getWeightLenCf()))
            && (this.getRequiredWeight() == null ? other.getRequiredWeight() == null : this.getRequiredWeight().equals(other.getRequiredWeight()))
            && (this.getCreateduser() == null ? other.getCreateduser() == null : this.getCreateduser().equals(other.getCreateduser()))
            && (this.getCreateddate() == null ? other.getCreateddate() == null : this.getCreateddate().equals(other.getCreateddate()))
            && (this.getLstupdateuser() == null ? other.getLstupdateuser() == null : this.getLstupdateuser().equals(other.getLstupdateuser()))
            && (this.getLstupdatedate() == null ? other.getLstupdatedate() == null : this.getLstupdatedate().equals(other.getLstupdatedate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShipBatch() == null) ? 0 : getShipBatch().hashCode());
        result = prime * result + ((getFabricType() == null) ? 0 : getFabricType().hashCode());
        result = prime * result + ((getFabricNo() == null) ? 0 : getFabricNo().hashCode());
        result = prime * result + ((getColor() == null) ? 0 : getColor().hashCode());
        result = prime * result + ((getMatGrp() == null) ? 0 : getMatGrp().hashCode());
        result = prime * result + ((getCustomer() == null) ? 0 : getCustomer().hashCode());
        result = prime * result + ((getRollMode() == null) ? 0 : getRollMode().hashCode());
        result = prime * result + ((getCondition() == null) ? 0 : getCondition().hashCode());
        result = prime * result + ((getCorrectionFactor() == null) ? 0 : getCorrectionFactor().hashCode());
        result = prime * result + ((getWeightLenCf() == null) ? 0 : getWeightLenCf().hashCode());
        result = prime * result + ((getRequiredWeight() == null) ? 0 : getRequiredWeight().hashCode());
        result = prime * result + ((getCreateduser() == null) ? 0 : getCreateduser().hashCode());
        result = prime * result + ((getCreateddate() == null) ? 0 : getCreateddate().hashCode());
        result = prime * result + ((getLstupdateuser() == null) ? 0 : getLstupdateuser().hashCode());
        result = prime * result + ((getLstupdatedate() == null) ? 0 : getLstupdatedate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shipBatch=").append(shipBatch);
        sb.append(", fabricType=").append(fabricType);
        sb.append(", fabricNo=").append(fabricNo);
        sb.append(", color=").append(color);
        sb.append(", matGrp=").append(matGrp);
        sb.append(", customer=").append(customer);
        sb.append(", rollMode=").append(rollMode);
        sb.append(", condition=").append(condition);
        sb.append(", correctionFactor=").append(correctionFactor);
        sb.append(", weightLenCf=").append(weightLenCf);
        sb.append(", requiredWeight=").append(requiredWeight);
        sb.append(", createduser=").append(createduser);
        sb.append(", createddate=").append(createddate);
        sb.append(", lstupdateuser=").append(lstupdateuser);
        sb.append(", lstupdatedate=").append(lstupdatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}