package com.jiashi.dao;

import com.jiashi.domain.QcInspectionHeader;
import com.jiashi.domain.QcInspectionHeaderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QcInspectionHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    long countByExample(QcInspectionHeaderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int deleteByExample(QcInspectionHeaderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String shipBatch);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int insert(QcInspectionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int insertSelective(QcInspectionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    List<QcInspectionHeader> selectByExample(QcInspectionHeaderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    QcInspectionHeader selectByPrimaryKey(String shipBatch);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QcInspectionHeader record, @Param("example") QcInspectionHeaderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QcInspectionHeader record, @Param("example") QcInspectionHeaderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QcInspectionHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QC_INSPECTION_HEADER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QcInspectionHeader record);
}